<div class="wow-live-chat-modal" id="wow-live-chat-modal" data-wow-popup="live-chat" role="dialog" aria-modal="true" aria-labelledby="wow-live-chat-title" hidden aria-hidden="true">
  <aside class="wow-chat-app" id="wowChatApp" role="document" aria-label="We Offer Wellness live chat">
    <div class="wow-chat-app__chrome" aria-hidden="true"><span class="wow-chat-app__title">WOW live chat</span></div>
    <section class="wow-chat-screen is-active" data-live-chat-prechat>
      <header class="wow-chat-topbar"><div class="wow-chat-brand"><div class="wow-chat-brand__avatar">W<span class="wow-chat-brand__status"></span></div><div class="wow-chat-brand__copy"><strong>WOW support</strong><span>Online · replies usually within a few minutes</span></div></div><div class="wow-chat-actions"><button class="wow-chat-icon-btn" type="button" data-live-chat-minimise aria-label="Minimise chat">−</button><button class="wow-chat-icon-btn" type="button" data-live-chat-close aria-label="Close chat">×</button></div></header>
      <div class="wow-chat-scroll"><div class="wow-chat-intro"><p class="wow-chat-eyebrow">Join the chat</p><h2 id="wow-live-chat-title">How can we help?</h2><p>Tell us what you need and we’ll get you to the right person. No queues, no faceless ticket form, just the WOW team.</p><div class="wow-chat-highlights"><div class="wow-chat-highlight"><span>◇</span><strong>Private &amp; secure</strong><small>Your details stay with WOW.</small></div><div class="wow-chat-highlight"><span>◷</span><strong>Fast response</strong><small>Usually a few minutes.</small></div><div class="wow-chat-highlight"><span>♡</span><strong>Real people</strong><small>Speak with the WOW team.</small></div></div></div>
        <form class="wow-chat-form" data-live-chat-form novalidate><p class="wow-chat-section-label">What can we help with?</p><div class="wow-chat-topics"><button type="button" class="wow-chat-topic">Booking help</button><button type="button" class="wow-chat-topic">Choose a therapy</button><button type="button" class="wow-chat-topic">Existing booking</button><button type="button" class="wow-chat-topic">Practitioner question</button><button type="button" class="wow-chat-topic">Something else</button></div><div class="wow-chat-field" data-field="name"><label for="chatName">First name <span>Required</span></label><input class="wow-chat-control" id="chatName" name="first_name" autocomplete="given-name" required><small class="wow-chat-error">Please enter your first name.</small></div><div class="wow-chat-field" data-field="email"><label for="chatEmail">Email <span>Required · so we can follow up</span></label><input class="wow-chat-control" id="chatEmail" name="email" type="email" autocomplete="email" required><small class="wow-chat-error">Please enter a valid email address.</small></div><div class="wow-chat-field" data-field="message" hidden><label for="chatMessage">Message <span>Required</span></label><textarea class="wow-chat-control" id="chatMessage" name="message" rows="4" required disabled aria-disabled="true" placeholder="Enter your first name and email to write a message…"></textarea><small class="wow-chat-error">Please add a short message.</small></div><label class="wow-chat-option"><input name="subscribe" type="checkbox" value="1"><span>Add me to the WOW newsletter for new wellness experiences, guides and offers.</span></label><button class="wow-chat-submit" type="submit" disabled aria-disabled="true">Join chat <span aria-hidden="true">→</span></button><p class="wow-chat-status" data-live-chat-status role="status" aria-live="polite"></p><p class="wow-chat-legal">By joining the chat you agree that WOW can use the details above to respond to your enquiry.</p></form>
      </div>
    </section>
    <section class="wow-chat-screen" data-live-chat-thread hidden><header class="wow-chat-topbar"><div class="wow-chat-brand"><div class="wow-chat-brand__avatar" data-live-chat-avatar>W<span class="wow-chat-brand__status"></span></div><div class="wow-chat-brand__copy"><strong data-live-chat-name>WOW support</strong><span data-live-chat-agent-status>Connecting…</span></div></div><div class="wow-chat-actions"><button class="wow-chat-icon-btn" type="button" data-live-chat-minimise aria-label="Minimise chat">−</button><button class="wow-chat-icon-btn" type="button" data-live-chat-close aria-label="Close chat">×</button></div></header><div class="wow-chat-context"><div><small>Status</small><strong data-live-chat-context-status>Active chat</strong></div><div><small>Page</small><strong data-live-chat-context-page>Current page</strong></div><div><small>Location</small><strong>WOW support</strong></div></div><div class="wow-chat-messages" data-live-chat-messages aria-live="polite"></div><p class="wow-chat-typing-label" data-live-chat-typing-label hidden>WOW team is typing…</p><div class="wow-chat-typing-row" data-live-chat-typing-row hidden><div class="wow-chat-message__avatar">W</div><div class="wow-chat-typing"><span></span><span></span><span></span></div></div><form class="wow-chat-compose" data-live-chat-reply><div class="wow-chat-quick"><button type="button">Send availability</button><button type="button">Ask location</button><button type="button">Share offering</button></div><div class="wow-chat-compose__row"><textarea name="message" rows="1" placeholder="Write a message…" aria-label="Write a message" required></textarea><button class="wow-chat-send" type="submit" aria-label="Send message">→</button></div><div class="wow-chat-compose__meta"><span class="wow-chat-live-state" data-live-chat-thread-status>We’ll reply as soon as someone is available.</span><span>Enter to send · Shift + Enter for new line</span></div></form></section>
  </aside>
</div>
