<div class="wow-wellness-match-modal" id="wow-wellness-match-modal" data-wow-popup="wellness-match" role="dialog" aria-modal="true" aria-labelledby="wow-wellness-match-title" hidden aria-hidden="true">
  <aside class="wow-wellness-match-sheet" data-wellness-match-sheet data-scene="1" role="document">
    <div class="wow-wellness-match-bg" aria-hidden="true"><span class="wow-wellness-orb wow-wellness-orb--a"></span><span class="wow-wellness-orb wow-wellness-orb--b"></span><span class="wow-wellness-orb wow-wellness-orb--c"></span><span class="wow-wellness-wave"></span></div>
    <header class="wow-wellness-match-top">
      <a class="wow-wellness-match-brand" href="/" aria-label="We Offer Wellness home"><span class="wow-wellness-match-brand-logo" aria-hidden="true"></span></a>
      <button type="button" class="wow-wellness-match-close" data-wow-popup-close aria-label="Close wellness match"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></button>
    </header>
    <div class="wow-wellness-match-intro"><h2 id="wow-wellness-match-title">Find your wellness match</h2><p>A few quick questions. No jargon, no guesswork.</p></div>
    <div class="wow-wellness-match-progress">
      <div class="wow-wellness-match-progress__meta"><span data-wellness-step-label>Loading your questions…</span><span data-wellness-step-percent></span></div>
      <div class="wow-wellness-match-progress__track" role="progressbar" aria-label="Form progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span data-wellness-progress-bar></span></div>
    </div>
    <div class="wow-wellness-match-content" data-wellness-match-content aria-live="polite"><div class="wow-wellness-match-loading">Preparing your wellness questions…</div></div>
    <p class="wow-wellness-match-error" data-wellness-match-error hidden></p>
    <footer class="wow-wellness-match-footer"><button type="button" class="btn-wow btn-wow--outline btn-wow--md" data-wellness-back hidden>Back</button><button type="button" class="btn-wow btn-wow--primary btn-wow--md wow-wellness-match-next" data-wellness-next disabled>Continue</button></footer>
  </aside>
</div>

<style>
.wow-wellness-match-modal{display:flex;justify-content:flex-end;align-items:stretch;min-height:100dvh;height:100%;pointer-events:none;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:#101828}.wow-wellness-match-modal[hidden]{display:none!important}
.wow-wellness-match-sheet{position:relative;isolation:isolate;width:min(560px,100vw);height:100dvh;max-height:100dvh;background:#fffdfa;display:flex;flex-direction:column;pointer-events:auto;box-shadow:-24px 0 70px rgba(16,24,40,.18);overflow:hidden;animation:wowWellnessMatchIn .36s cubic-bezier(.22,.8,.24,1)}
.wow-wellness-match-bg{position:absolute;inset:0;z-index:-1;overflow:hidden;background:linear-gradient(180deg,rgba(255,253,250,.97),rgba(255,253,250,.93) 54%,rgba(240,247,244,.97));pointer-events:none}.wow-wellness-orb{position:absolute;border-radius:999px;opacity:.75;transition:transform .8s cubic-bezier(.2,.8,.2,1)}.wow-wellness-orb--a{width:420px;height:420px;right:-220px;bottom:-160px;background:rgba(84,148,131,.16)}.wow-wellness-orb--b{width:310px;height:310px;left:-180px;bottom:-70px;background:rgba(217,199,167,.2)}.wow-wellness-orb--c{width:150px;height:150px;right:70px;top:120px;background:rgba(62,116,103,.09)}.wow-wellness-wave{position:absolute;left:-8%;right:-8%;bottom:-145px;height:260px;background:rgba(84,148,131,.1);border-radius:50% 45% 0 0/34% 35% 0 0;transform:rotate(-3deg);transition:transform .8s ease,bottom .8s ease}
.wow-wellness-match-sheet[data-scene="2"] .wow-wellness-orb--a{transform:translate(-30px,-40px) scale(1.05)}.wow-wellness-match-sheet[data-scene="3"] .wow-wellness-orb--b{transform:translate(80px,-30px) scale(.9)}.wow-wellness-match-sheet[data-scene="4"] .wow-wellness-orb--a{transform:translate(-120px,20px) scale(.86)}.wow-wellness-match-sheet[data-scene="5"] .wow-wellness-orb--c{transform:translate(-95px,170px) scale(1.7)}.wow-wellness-match-sheet[data-scene="6"] .wow-wellness-wave{transform:rotate(4deg) translateY(-65px)}.wow-wellness-match-sheet[data-scene="7"] .wow-wellness-orb--a{transform:translate(-70px,-100px) scale(1.15)}.wow-wellness-match-sheet[data-scene="8"] .wow-wellness-orb--b{transform:translate(160px,-80px) scale(.72)}.wow-wellness-match-sheet[data-scene="9"] .wow-wellness-wave{bottom:-80px;transform:rotate(-6deg) scaleX(1.1)}
.wow-wellness-match-top{padding:20px 28px 12px;display:flex;align-items:center;justify-content:space-between;flex:0 0 auto}.wow-wellness-match-brand{display:inline-flex;align-items:center;color:#101828;text-decoration:none}.wow-wellness-match-brand-logo,.wow-wellness-match-brand-logo svg{display:block;height:18px;width:auto}.wow-wellness-match-close{width:40px;height:40px;min-width:40px;border:1px solid #d0d5dd;border-radius:2px;background:#fff;color:#101828;display:grid;place-items:center;cursor:pointer}.wow-wellness-match-close:hover{background:#f9fafb}.wow-wellness-match-close:focus-visible{outline:2px solid #3e7467;outline-offset:2px}
.wow-wellness-match-intro{padding:2px 28px 8px}.wow-wellness-match-intro h2{font-family:"Playfair Display",Georgia,serif;font-size:34px;font-weight:750;line-height:1.05;letter-spacing:-.025em;margin:0 0 8px}.wow-wellness-match-intro p{margin:0;color:#475467;font-size:14px;line-height:1.55}.wow-wellness-match-progress{padding:16px 28px 0}.wow-wellness-match-progress__meta{display:flex;justify-content:space-between;gap:14px;margin-bottom:9px;color:#667085;font-size:11px;font-weight:600}.wow-wellness-match-progress__track{height:3px;background:#e4e7ec}.wow-wellness-match-progress__track span{display:block;width:0;height:100%;background:#549483;transition:width .45s cubic-bezier(.2,.8,.2,1)}
.wow-wellness-match-content{flex:1 1 auto;min-height:0;overflow-y:auto;padding:26px 28px 130px;scrollbar-width:thin}.wow-wellness-match-step{animation:wowWellnessStepIn .38s cubic-bezier(.2,.8,.2,1)}.wow-wellness-match-kicker{margin:0 0 12px;color:#3e7467;font-size:10px;font-weight:700;letter-spacing:.2em;text-transform:uppercase}.wow-wellness-match-step h3{font-family:"Playfair Display",Georgia,serif;font-size:34px;line-height:1.08;font-weight:750;letter-spacing:-.025em;margin:0 0 10px}.wow-wellness-match-description{margin:0 0 22px;color:#475467;font-size:14px;line-height:1.6}
.wow-wellness-options{display:grid;grid-template-columns:1fr 1fr;gap:10px}.wow-wellness-option{position:relative;border:1px solid #d0d5dd;background:rgba(255,255,255,.88);padding:14px;min-height:64px;cursor:pointer;transition:.18s ease;display:flex;align-items:center;gap:12px;border-radius:2px;user-select:none}.wow-wellness-option:hover{border-color:#98a2b3;transform:translateY(-1px);box-shadow:0 7px 18px rgba(16,24,40,.05)}.wow-wellness-option.is-selected{border-color:#549483;background:#f0f7f4;box-shadow:inset 0 0 0 1px #549483}.wow-wellness-option input{position:absolute;opacity:0;pointer-events:none}.wow-wellness-option__dot{width:20px;height:20px;flex:0 0 20px;border:1px solid #98a2b3;border-radius:50%;display:grid;place-items:center;background:#fff}.wow-wellness-option--multi .wow-wellness-option__dot{border-radius:2px}.wow-wellness-option.is-selected .wow-wellness-option__dot{border-color:#549483;background:#549483}.wow-wellness-option.is-selected .wow-wellness-option__dot:after{content:"";width:6px;height:6px;border-radius:50%;background:#fff}.wow-wellness-option--multi.is-selected .wow-wellness-option__dot:after{content:"✓";width:auto;height:auto;background:none;color:#fff;font-size:13px;font-weight:800}.wow-wellness-option__key{margin-left:auto;color:#667085;font-size:10px}.wow-wellness-option__label{font-size:13px;font-weight:650;line-height:1.3}
.wow-wellness-field{display:block;width:100%;min-height:52px;border:1px solid #cfd8d5;border-radius:2px;background:#fff;padding:12px;font:inherit;color:#101828}.wow-wellness-field:focus{outline:2px solid #549483;outline-offset:-2px}.wow-wellness-field--area{min-height:120px;resize:vertical}.wow-wellness-field-label{display:block;margin:0 0 8px;font-size:12px;font-weight:700}.wow-wellness-match-validation,.wow-wellness-match-error{margin:12px 28px 0;color:#b42318;font-size:12px;font-weight:600}.wow-wellness-match-validation{margin-left:0;margin-right:0}.wow-wellness-match-loading{color:#667085;font-size:14px}.wow-wellness-match-complete{padding-top:12px}.wow-wellness-match-complete__mark{width:54px;height:54px;display:grid;place-items:center;background:#e4f2ed;color:#315e53;border-radius:50%;font-size:24px;margin-bottom:18px}
.wow-wellness-match-footer{position:absolute;left:0;right:0;bottom:0;padding:14px 28px 18px;background:linear-gradient(180deg,rgba(255,253,250,0),rgba(255,253,250,.96) 25%,#fffdfa 52%);z-index:4;display:flex;gap:10px;align-items:center}.wow-wellness-match-next{flex:1;justify-content:center}.wow-wellness-match-footer [hidden]{display:none!important}@keyframes wowWellnessMatchIn{from{opacity:.35;transform:translateX(38px)}to{opacity:1;transform:translateX(0)}}@keyframes wowWellnessStepIn{from{opacity:0;transform:translateX(22px)}to{opacity:1;transform:none}}
@media(max-width:575px){.wow-wellness-match-sheet{width:100vw}.wow-wellness-match-top{padding:14px 18px 8px}.wow-wellness-match-intro{padding:0 18px 6px}.wow-wellness-match-intro h2{font-size:30px}.wow-wellness-match-progress{padding:12px 18px 0}.wow-wellness-match-content{padding:22px 18px 122px}.wow-wellness-match-step h3{font-size:31px}.wow-wellness-options{grid-template-columns:1fr}.wow-wellness-match-footer{padding:12px 18px 16px}}@media(prefers-reduced-motion:reduce){.wow-wellness-match-sheet,.wow-wellness-match-step,.wow-wellness-orb,.wow-wellness-wave{animation:none!important;transition:none!important}}
</style>

<script data-cfasync="false">
(() => {
  const modal=document.getElementById('wow-wellness-match-modal');if(!modal||modal.dataset.wellnessBound==='true')return;modal.dataset.wellnessBound='true';
  const navLogo=document.querySelector('.wow-brand-mark svg'),drawerLogo=modal.querySelector('.wow-wellness-match-brand-logo');if(navLogo&&drawerLogo)drawerLogo.replaceChildren(navLogo.cloneNode(true));
  const sheet=modal.querySelector('[data-wellness-match-sheet]'),host=modal.querySelector('[data-wellness-match-content]'),back=modal.querySelector('[data-wellness-back]'),next=modal.querySelector('[data-wellness-next]'),error=modal.querySelector('[data-wellness-match-error]'),label=modal.querySelector('[data-wellness-step-label]'),percent=modal.querySelector('[data-wellness-step-percent]'),bar=modal.querySelector('[data-wellness-progress-bar]'),progress=bar?.parentElement;
  let config=null,questions=[],answers={},history=[],index=0,started=Date.now(),submitting=false,redirectTimer=null;
  const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const uuid=()=>crypto.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,char=>{const value=Math.random()*16|0;return(char==='x'?value:(value&3|8)).toString(16)});
  const visitorToken=()=>{const found=document.cookie.match(/(?:^|; )wow_visitor_id=([^;]*)/);if(found?.[1])return decodeURIComponent(found[1]);const value=uuid();document.cookie=`wow_visitor_id=${encodeURIComponent(value)}; Max-Age=315360000; Path=/; SameSite=Lax`;return value};
  const progressKey=()=>`wowWellnessMatchProgress:${visitorToken()}`;
  const saveProgress=(questionId=current()?.id)=>{try{localStorage.setItem(progressKey(),JSON.stringify({formSlug:config?.form?.slug||String(config?.form?.id||''),answers,history,currentQuestionId:questionId,started,updatedAt:Date.now()}))}catch{}};
  const loadProgress=()=>{try{const saved=JSON.parse(localStorage.getItem(progressKey())||'null');if(!saved||saved.formSlug!==(config?.form?.slug||String(config?.form?.id||''))||Date.now()-Number(saved.updatedAt||0)>2592000000)return null;return saved}catch{return null}};
  const clearProgress=()=>{try{localStorage.removeItem(progressKey())}catch{}};
  const trackBehaviour=(eventType,metadata={})=>{try{const origin=new URL(config?.form?.submit_url||'https://studio.weofferwellness.co.uk').origin;fetch(`${origin}/api/behaviour/events`,{method:'POST',credentials:'include',keepalive:true,headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({events:[{event_uuid:uuid(),event_type:eventType,occurred_at:new Date().toISOString(),sequence:Date.now(),page_context:location.pathname.slice(0,255),metadata:{surface:'wellness_match_finder',page_type:'wellness_match',form_slug:config?.form?.slug||'',device_class:matchMedia('(max-width:767px)').matches?'mobile':matchMedia('(max-width:1024px)').matches?'tablet':'desktop',...metadata}}]})}).catch(()=>{})}catch{}};
  const qType=q=>({choice:'radio',multi:'checkbox',textarea:'long_text',text:'short_text'}[q.type]||q.type);
  const compare=(actual,op,expected)=>op==='equals'?String(actual)===String(expected):op==='does not equal'?String(actual)!==String(expected):op==='contains'?(Array.isArray(actual)?actual.includes(expected):String(actual??'').toLowerCase().includes(String(expected).toLowerCase())):op==='greater than'?Number(actual)>Number(expected):op==='less than'?Number(actual)<Number(expected):false;
  const visible=()=>questions.filter(q=>{const rules=config?.form?.definition?.rules||[],shows=rules.filter(r=>r.target===q.id&&r.action==='show'),hides=rules.filter(r=>r.target===q.id&&r.action==='hide');if(shows.length&&!shows.some(r=>compare(answers[r.source],r.operator,r.value)))return false;return !hides.some(r=>compare(answers[r.source],r.operator,r.value));});
  const answered=q=>{if(['statement','divider'].includes(qType(q)))return true;const value=answers[q.id];return Array.isArray(value)?value.length>0:value!==undefined&&value!==null&&String(value).trim()!=='';};
  const updateProgress=complete=>{const list=visible(),current=complete?list.length:Math.min(index+1,list.length),value=complete?100:Math.round((current/Math.max(1,list.length))*100);label.textContent=complete?'Complete':`Step ${current} of ${list.length}`;percent.textContent=`${value}%`;bar.style.width=`${value}%`;progress?.setAttribute('aria-valuenow',String(value));sheet.dataset.scene=String(Math.min(current,10));};
  const options=(q,multi)=>(q.options||[]).map((option,i)=>{const selected=multi?(answers[q.id]||[]).includes(option):answers[q.id]===option,key=i<9?String(i+1):String.fromCharCode(65+i);return `<label class="wow-wellness-option ${multi?'wow-wellness-option--multi':''} ${selected?'is-selected':''}"><input type="${multi?'checkbox':'radio'}" name="wellness_${esc(q.id)}" value="${esc(option)}" ${selected?'checked':''}><span class="wow-wellness-option__dot"></span><span class="wow-wellness-option__label">${esc(option)}</span><span class="wow-wellness-option__key">${key}</span></label>`;}).join('');
  const field=q=>{const type=qType(q),value=answers[q.id]??'';if(['radio','choice'].includes(type))return `<div class="wow-wellness-options">${options(q,false)}</div>`;if(['checkbox','multi'].includes(type))return `<div class="wow-wellness-options">${options(q,true)}</div>`;if(type==='dropdown')return `<label class="wow-wellness-field-label" for="wellness_${esc(q.id)}">Choose an option</label><select class="wow-wellness-field" id="wellness_${esc(q.id)}"><option value="">Choose…</option>${(q.options||[]).map(o=>`<option ${value===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`;if(type==='long_text')return `<label class="wow-wellness-field-label" for="wellness_${esc(q.id)}">Your answer</label><textarea class="wow-wellness-field wow-wellness-field--area" id="wellness_${esc(q.id)}" placeholder="${esc(q.placeholder||'Type your answer…')}">${esc(value)}</textarea>`;if(['rating','nps'].includes(type)){const min=type==='nps'?0:Number(q.min||1),max=type==='nps'?10:Number(q.max||5);return `<div class="wow-wellness-options">${Array.from({length:max-min+1},(_,i)=>{const option=String(i+min);return `<button type="button" class="wow-wellness-option ${String(value)===option?'is-selected':''}" data-wellness-rating="${option}"><span class="wow-wellness-option__label">${option}</span></button>`}).join('')}</div>`;}if(['statement','divider'].includes(type))return '';const inputType=['email','number','phone','date','time'].includes(type)?(type==='phone'?'tel':type):'text';return `<label class="wow-wellness-field-label" for="wellness_${esc(q.id)}">Your answer</label><input class="wow-wellness-field" id="wellness_${esc(q.id)}" type="${inputType}" value="${esc(value)}" placeholder="${esc(q.placeholder||'Type your answer…')}">`;};
  const current=()=>visible()[index];
  const unavailable=message=>{host.innerHTML=`<section class="wow-wellness-match-step"><p class="wow-wellness-match-kicker">Find your wellness match</p><h3>We’ll be right back.</h3><p class="wow-wellness-match-description">${esc(message)}</p>${config?.form?.share_url?`<a class="btn-wow btn-wow--outline btn-wow--md" href="${esc(config.form.share_url)}">Open the full form</a>`:''}</section>`;next.hidden=true;back.hidden=true;label.textContent='Unavailable';percent.textContent='';bar.style.width='0';};
  const render=()=>{const list=visible();if(!list.length)return unavailable('This matcher does not have any published questions yet.');if(index>=list.length)index=list.length-1;const q=list[index];host.innerHTML=`<section class="wow-wellness-match-step" data-question-id="${esc(q.id)}"><p class="wow-wellness-match-kicker">Your wellness match</p><h3>${esc(q.title)}</h3>${q.description?`<p class="wow-wellness-match-description">${esc(q.description)}</p>`:''}${field(q)}<p class="wow-wellness-match-validation" hidden>Please answer this question.</p></section>`;back.hidden=index===0;next.hidden=false;next.disabled=false;next.textContent=index===list.length-1?'See my matches':'Continue';error.hidden=true;updateProgress(false);saveProgress(q.id);trackBehaviour('wellness_match_step_viewed',{question_id:q.id,question_title:q.title,step_index:index+1,step_total:list.length});host.scrollTop=0;host.querySelector('input:not([type="radio"]):not([type="checkbox"]),textarea,select')?.focus({preventScroll:true});};
  const validation=message=>{const node=host.querySelector('.wow-wellness-match-validation');if(node){node.textContent=message;node.hidden=false;}};
  const validate=q=>{if(q.required&&!answered(q))return'Please answer this question.';const value=answers[q.id];if(value&&qType(q)==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return'Enter a valid email address.';return'';};
  const actionFor=q=>(config?.form?.definition?.rules||[]).find(r=>r.source===q.id&&compare(answers[q.id],r.operator,r.value)&&['jump to','end form'].includes(r.action));
  const submit=async()=>{submitting=true;next.disabled=true;next.textContent='Finding matches…';error.hidden=true;try{const response=await fetch(config.form.submit_url,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({responses:answers,elapsed_ms:Date.now()-started})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(payload.message||'We could not save your answers.'),{errors:payload.errors||{}});const answerRows=questions.map(question=>({question:question.title||'',values:Array.isArray(answers[question.id])?answers[question.id]:[answers[question.id]]})).map(row=>({...row,values:row.values.filter(value=>value!==undefined&&value!==null&&String(value).trim()!=='').map(String)})).filter(row=>row.values.length);sessionStorage.setItem('wowWellnessMatchResults',JSON.stringify({answers:answerRows,completedAt:new Date().toISOString()}));trackBehaviour('wellness_match_completed',{step_total:visible().length});clearProgress();host.innerHTML=`<section class="wow-wellness-match-step wow-wellness-match-complete"><div class="wow-wellness-match-complete__mark">✓</div><p class="wow-wellness-match-kicker">Your matches are ready</p><h3>Thanks — you’re all done.</h3><p class="wow-wellness-match-description">Your response has been recorded.</p><p class="wow-wellness-match-description">Taking you to your personalised matches…</p><div class="wow-button-row"><a class="btn-wow btn-wow--primary btn-wow--md" href="/wellness-match-finder/results">Explore your wellness matches</a><button class="btn-wow btn-wow--outline btn-wow--md" type="button" data-wellness-start-over>Start again</button></div></section>`;back.hidden=true;next.hidden=true;updateProgress(true);host.scrollTop=0;redirectTimer=window.setTimeout(()=>window.location.href='/wellness-match-finder/results',2500);}catch(exception){const first=Object.values(exception.errors||{})[0];error.textContent=Array.isArray(first)?first[0]:(first||exception.message);error.hidden=false;next.disabled=false;next.textContent='Try again';}finally{submitting=false;}};
  const goNext=()=>{if(submitting)return;const q=current();if(!q)return;const message=validate(q);if(message)return validation(message);const action=actionFor(q);if(action?.action==='end form')return submit();history.push(q.id);const list=visible();if(action?.action==='jump to'){const target=list.findIndex(item=>item.id===action.target);index=target>index?target:index+1;}else index+=1;if(index>=list.length)submit();else render();};
  const goBack=()=>{const previousId=history.pop();if(previousId){const previous=visible().findIndex(item=>item.id===previousId);index=Math.max(0,previous);}else index=Math.max(0,index-1);render();};
  const startOver=()=>{window.clearTimeout(redirectTimer);redirectTimer=null;clearProgress();sessionStorage.removeItem('wowWellnessMatchResults');answers={};history=[];index=0;started=Date.now();submitting=false;trackBehaviour('wellness_match_reset',{interaction:'start_again'});render();};
  const syncOptionSelection=()=>host.querySelectorAll('.wow-wellness-option').forEach(option=>{const input=option.querySelector('input');if(input)option.classList.toggle('is-selected',input.checked);});
  host.addEventListener('change',event=>{const q=current();if(!q)return;const target=event.target;let rejected=false;if(target.matches('input[type="checkbox"]')){const checked=[...host.querySelectorAll('input[type="checkbox"]:checked')],maximum=Number(q.max||0);if(maximum>0&&checked.length>maximum){target.checked=false;rejected=true;validation(`Choose up to ${maximum} options.`);}answers[q.id]=[...host.querySelectorAll('input[type="checkbox"]:checked')].map(input=>input.value);}else if(target.matches('input[type="radio"]'))answers[q.id]=target.value;else answers[q.id]=target.value;syncOptionSelection();if(!rejected){host.querySelector('.wow-wellness-match-validation')?.setAttribute('hidden','');saveProgress(q.id);trackBehaviour('wellness_match_answered',{question_id:q.id,question_title:q.title,answer_values:(Array.isArray(answers[q.id])?answers[q.id]:[answers[q.id]]).map(String),step_index:index+1,step_total:visible().length});}if(q.autoAdvance&&target.matches('input[type="radio"]'))window.setTimeout(goNext,180);});
  host.addEventListener('input',event=>{const q=current();if(q&&event.target.matches('input,textarea')){answers[q.id]=event.target.value;saveProgress(q.id);}});host.addEventListener('click',event=>{const restart=event.target.closest('[data-wellness-start-over]');if(restart){startOver();return}const rating=event.target.closest('[data-wellness-rating]');if(!rating)return;const q=current();answers[q.id]=Number(rating.dataset.wellnessRating);host.querySelectorAll('[data-wellness-rating]').forEach(option=>option.classList.toggle('is-selected',option===rating));host.querySelector('.wow-wellness-match-validation')?.setAttribute('hidden','');saveProgress(q.id);trackBehaviour('wellness_match_answered',{question_id:q.id,question_title:q.title,answer_values:[String(answers[q.id])],step_index:index+1,step_total:visible().length});if(q.autoAdvance)window.setTimeout(goNext,180);});next.addEventListener('click',goNext);back.addEventListener('click',goBack);
  modal.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.target.matches('textarea')){event.preventDefault();goNext();return;}if(event.key==='Backspace'&&!event.target.matches('input,textarea,select')){event.preventDefault();goBack();return;}if(!event.target.matches('input,textarea,select')&&/^[1-9a-z]$/i.test(event.key)){const choices=[...host.querySelectorAll('.wow-wellness-option input')],key=event.key.toLowerCase(),choiceIndex=/^\d$/.test(key)?Number(key)-1:key.charCodeAt(0)-97+9;choices[choiceIndex]?.click();}});
  document.addEventListener('wow:popup-closed',event=>{if(event.detail?.key==='wellness-match'){document.body.style.overflow='';document.querySelector('[data-wow-popup-trigger="wellness-match"]')?.setAttribute('aria-expanded','false');}});
  window.WOWWellnessMatch={open(popupConfig){config=popupConfig;window.clearTimeout(redirectTimer);redirectTimer=null;const saved=loadProgress();answers=saved?.answers||{};history=Array.isArray(saved?.history)?saved.history:[];index=0;started=Number(saved?.started||Date.now());document.body.style.overflow='hidden';document.querySelector('[data-wow-popup-trigger="wellness-match"]')?.setAttribute('aria-expanded','true');if(!config?.form?.definition?.questions)unavailable('The linked WOW Form is not available.');else{questions=config.form.definition.questions;const resumeIndex=saved?.currentQuestionId?visible().findIndex(question=>question.id===saved.currentQuestionId):-1;if(resumeIndex>=0)index=resumeIndex;trackBehaviour('wellness_match_opened',{resumed:!!saved,step_index:index+1,step_total:visible().length});render();}window.setTimeout(()=>modal.querySelector('[data-wow-popup-close]')?.focus(),180);}};
})();
</script>
