<?php

return [
    'pages' => [
        'home' => [
            'default_layout' => [
                ['component' => 'hero-slider', 'enabled' => true, 'config' => []],
                ['component' => 'popular_searches', 'enabled' => true, 'config' => []],
                ['component' => 'schedule', 'enabled' => true, 'config' => []],
                ['component' => 'latest_catalogue', 'enabled' => true, 'config' => []],
                ['component' => 'discover_category', 'enabled' => true, 'config' => []],
                ['component' => 'gift_cards_occasion', 'enabled' => true, 'config' => []],
                ['component' => 'no-travel-needed', 'enabled' => true, 'config' => []],
                ['component' => 'gifts', 'enabled' => true, 'config' => []],
                ['component' => 'mindful_times_ribbon', 'enabled' => true, 'config' => []],
                ['component' => 'trust-feel-safe', 'enabled' => true, 'config' => []],
                ['component' => 'mindfultimes_guides_interviews', 'enabled' => true, 'config' => []],
                ['component' => 'practitioner_chats_converstions', 'enabled' => true, 'config' => []],
                ['component' => 'our_approach', 'enabled' => true, 'config' => []],
            ],
        ],
    ],

    'components' => [
        'legacy_content' => ['view' => null],
        'page_content' => ['view' => null],
        'breadcrumbs' => ['view' => null],
        'landing_hero' => ['view' => null],
        'hero_meta' => ['view' => null],
        'search_bar' => ['view' => null],
        'popular_price' => ['view' => null],
        'faq' => ['view' => null],
        'related_pages' => ['view' => null],
        'guide_panel' => ['view' => null],
        'modality_board' => ['view' => null],
        'location_explorer' => ['view' => null],
        'location_search_summary' => ['view' => null],
        'nearby_locations' => ['view' => null],
        'featured_locations' => ['view' => null],
        'location_directory' => ['view' => null],
        'location_nearby_offerings' => ['view' => null],
        'location_popular_places' => ['view' => null],
        'location_new_nearby' => ['view' => null],
        'location_price_bands' => ['view' => null],
        'location_online_offerings' => ['view' => null],
        'location_search' => ['view' => null],
        'route_options' => ['view' => null],
        'giftcards_catalogue' => ['view' => null],
        'seo_location_search' => ['view' => null],
        'seo_results' => ['view' => null],
        'collection_results' => ['view' => null],
        'needs_grid' => ['view' => null],
        'quick_browse' => ['view' => null],
        'trust_panel' => ['view' => null],
        'schedule_discovery' => ['view' => null],
        'schedule_links' => ['view' => null],
        'schedule_days' => ['view' => null],
        'schedule_featured' => ['view' => null],
        'schedule_online' => ['view' => null],
        'schedule_upcoming' => ['view' => null],
        'schedule_discovery_cards' => ['view' => null],
        'schedule_content' => ['view' => null],
        'provider_directory' => ['view' => null],
        'provider_hero' => ['view' => null],
        'provider_navigation' => ['view' => null],
        'provider_overview' => ['view' => null],
        'provider_about' => ['view' => null],
        'provider_credentials' => ['view' => null],
        'provider_offerings' => ['view' => null],
        'provider_locations' => ['view' => null],
        'provider_reviews' => ['view' => null],
        'offering_body' => ['view' => null],
        'guide_hub_content' => ['view' => null],
        'guide_article_content' => ['view' => null],
        'guide_article_rail' => ['view' => null],
        'about_hero' => ['view' => null],
        'about_story' => ['view' => null],
        'about_founders' => ['view' => null],
        'about_vision_mission' => ['view' => null],
        'contact_hero' => ['view' => null],
        'contact_topics' => ['view' => null],
        'contact_details' => ['view' => null],
        'help_hero' => ['view' => null],
        'help_content' => ['view' => null],
        'help_giftcards_content' => ['view' => null],
        'wellness_match_results' => ['view' => null],
        'partners_hero' => ['view' => null],
        'partners_model' => ['view' => null],
        'partners_marketplace' => ['view' => null],
        'partners_profile' => ['view' => null],
        'partners_studio' => ['view' => null],
        'partners_cta' => ['view' => null],
        'corporate_hero' => ['view' => null],
        'corporate_content' => ['view' => null],
        'safety_content' => ['view' => null],
        'safety_note' => ['view' => null],
        'hero-slider' => ['view' => 'home.sections.hero-slider'],
        'popular_searches' => ['view' => 'home.sections.popular_searches'],
        'schedule' => ['view' => 'home.sections.schedule', 'condition' => 'hasClassesThisWeek'],
        'latest_catalogue' => ['view' => 'home.sections.latest_catalogue'],
        'collection_rail' => ['view' => 'home.sections.collection_rail'],
        'offering_tabs' => ['view' => 'home.sections.offering_tabs'],
        'offering_filters' => ['view' => 'home.sections.offering_filters'],
        'discover_category' => ['view' => 'home.sections.discover_category'],
        'gift_cards_occasion' => ['view' => 'home.sections.gift_cards_occasion'],
        'no-travel-needed' => ['view' => 'home.sections.no-travel-needed'],
        'gifts' => ['view' => 'home.sections.gifts'],
        'mindful_times_ribbon' => ['view' => 'home.sections.mindful_times_ribbon'],
        'trust-feel-safe' => ['view' => 'home.sections.trust-feel-safe'],
        'mindfultimes_guides_interviews' => ['view' => 'home.sections.mindfultimes_guides_interviews'],
        'practitioner_chats_converstions' => ['view' => 'home.sections.practitioner_chats_converstions'],
        'our_approach' => ['view' => 'home.sections.our_approach', 'wrapper' => 'container'],
    ],
];
